services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat

  app:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db


volumes:
  postgres_data: